In [2]:
import spacy
import pandas as pd

In [3]:
nlp = spacy.load('en_core_web_sm')

In [5]:
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy \
disposition seemed to unte some of the blest blessings of existence and had lived nearly twenty one years \
in the world with very little to distress or vex her she was the youngest of the two daighters of a most \
affectionate indulgent father and has in consequence of her sisters marriage been mistress of his \
house from a very early period her mother had died too long ago for her to have more \
than an indistinct remembrance of her caresses and her place had been supplied by an excellent \
woman as governess who had fallen little short of a mother in affection sixteen years"

In [6]:
print (emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unte some of the blest blessings of existence and had lived nearly twenty one years in the world with very little to distress or vex her she was the youngest of the two daighters of a most affectionate indulgent father and has in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years

In [7]:
spacy_doc = nlp(emma_ja)

In [8]:
print(spacy_doc)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unte some of the blest blessings of existence and had lived nearly twenty one years in the world with very little to distress or vex her she was the youngest of the two daighters of a most affectionate indulgent father and has in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years

In [10]:
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])

In [12]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token': token.text, 'pos_tag': token.pos_}])], ignore_index=True)

In [13]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [15]:
pos_df_counts = pos_df.groupby(['token', 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)

In [17]:
pos_df_counts.head(15)

     token pos_tag  counts
49      of     ADP       8
33     her    PRON       6
5      and   CCONJ       5
0        a     DET       4
28     had     AUX       4
64     the     DET       4
65      to    PART       3
37      in     ADP       3
78   years    NOUN       2
74    with     ADP       2
70    very     ADV       2
47  mother    NOUN       2
40  little     ADJ       2
7     been     AUX       2
4       an     DET       2

In [19]:
pos_df_poscounts = pos_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)

In [20]:
pos_df_poscounts.head(10)

pos_tag
NOUN     23
ADJ      15
ADP       7
VERB      7
ADV       6
PRON      5
AUX       4
NUM       4
DET       3
CCONJ     2
Name: token, dtype: int64

In [22]:
nouns = pos_df_counts[pos_df_counts.pos_tag == 'NOUN'][:10]
nouns

          token pos_tag  counts
78        years    NOUN       2
47       mother    NOUN       2
59      sisters    NOUN       1
54  remembrance    NOUN       1
53        place    NOUN       1
52       period    NOUN       1
8     blessings    NOUN       1
71          vex    NOUN       1
75        woman    NOUN       1
77        world    NOUN       1